gpr

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,52 +1,53 @@
 version: 2.1
 
-orbs:
-  win: circleci/windows@2.2.0
-  browser-tools: circleci/browser-tools@0.1.4
-
 parameters:
   run_integration_tests:
     type: boolean
     default: false
 
 orbs:
+  browser-tools: circleci/browser-tools@0.1.4
+  win: circleci/windows@2.2.0
+
   github-pull-request-info:
-    description: >
+    description: |
       Pulls in Github pull request data from the Github API
       https://developer.github.com/v3/pulls/#get-a-single-pull-request
     commands:
       inject:
-        if [ -z "$CIRCLE_PULL_REQUEST" ]
-          echo "Not a pull request. Skipping"
-          exit 0
-        fi
+        steps:
+        - run: |
+            if [ -z "$CIRCLE_PULL_REQUEST" ]
+              echo "Not a pull request. Skipping"
+              exit 0
+            fi
 
-        if ! [ -x "$(command -v curl)" ]; then
-          echo "Error: curl is not installed" >&2
-          exit 1
-        fi
+            if ! [ -x "$(command -v curl)" ]; then
+              echo "Error: curl is not installed" >&2
+              exit 1
+            fi
 
-        if ! [ -x "$(command -v jq)" ]; then
-          echo "Error: jq is not installed" >&2
-          exit 1
-        fi
+            if ! [ -x "$(command -v jq)" ]; then
+              echo "Error: jq is not installed" >&2
+              exit 1
+            fi
 
-        if [ -z "$GITHUB_PR_INFO_USERNAME" ]
-          echo "Error: \$GITHUB_PR_INFO_USERNAME is not set"
-          exit 1
-        fi
+            if [ -z "$GITHUB_PR_INFO_USERNAME" ]
+              echo "Error: \$GITHUB_PR_INFO_USERNAME is not set"
+              exit 1
+            fi
 
-        if [ -z "$GITHUB_PR_INFO_TOKEN" ]
-          echo "Error: \$GITHUB_PR_INFO_TOKEN is not set"
-          exit 1
-        fi
+            if [ -z "$GITHUB_PR_INFO_TOKEN" ]
+              echo "Error: \$GITHUB_PR_INFO_TOKEN is not set"
+              exit 1
+            fi
 
-        echo $CIRCLE_PULL_REQUEST
+            echo $CIRCLE_PULL_REQUEST
 
-        #curl https://api.github.com/repos/${OWNER}/${REPO}/pulls/${PULL_NUMBER} \
-        #  -u ${GITHUB_PR_INFO_USERNAME}:${GITHUB_PR_INFO_TOKEN} \
-        #  -H "Content-type: application/json" \
-        #  -i
+            #curl https://api.github.com/repos/${OWNER}/${REPO}/pulls/${PULL_NUMBER} \
+            #  -u ${GITHUB_PR_INFO_USERNAME}:${GITHUB_PR_INFO_TOKEN} \
+            #  -H "Content-type: application/json" \
+            #  -i
 
 
 jobs:
